Update useGetPathForRecordCallback.ts
Otherwise it gives errors while building:


node_modules/ra-core/src/routing/useGetPathForRecordCallback.ts:28:52 - error TS2339: Property 'hasShow' does not exist on type '{}'.

node_modules/ra-core/src/routing/useGetPathForRecordCallback.ts:30:38 - error TS2339: Property 'hasEdit' does not exist on type '{}'.